import type { Metadata } from "next";
import "./globals.css";
// import Navbar from "@/app/components/layouts/Navbar/index";
import Header from "@/app/components/layouts/Header";
import Sidebar from "@/app/components/layouts/Sidebar/Sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />

                <div className="wrap-layout">
                    <Sidebar />
                    <div>{children}</div>
                </div>
            </body>
        </html>
    );
}
